# Generated by Django 4.2.22 on 2025-08-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SignUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, help_text="Your name", max_length=150),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, help_text="Your email address", max_length=254
                    ),
                ),
            ],
        ),
    ]
