# Generated by Django 4.2.22 on 2025-08-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signup", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="signup",
            name="password",
            field=models.CharField(
                default="null", help_text="Your password", max_length=128
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="signup",
            name="email",
            field=models.EmailField(help_text="Your email address", max_length=254),
        ),
        migrations.AlterField(
            model_name="signup",
            name="name",
            field=models.CharField(help_text="Your name", max_length=150),
        ),
    ]
