# Generated by Django 4.2.22 on 2025-08-08 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("signup", "0002_signup_password_alter_signup_email_alter_signup_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SignUp",
        ),
    ]
