# Generated by Django 4.2.22 on 2025-06-05 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, help_text="(Optional) Your name", max_length=150
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="(Optional) Your email address",
                        max_length=254,
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Your feedback or prompt for TeachEra"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="DiscussionComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="(Optional) Your name (leave blank to post as Anonymous)",
                        max_length=150,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="(Optional) Your email (not displayed publicly)",
                        max_length=254,
                    ),
                ),
                ("body", models.TextField(help_text="Your comment or reply")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="(Optional) If this is a reply, select the parent comment",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="feedback_discussion.discussioncomment",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
