# Generated by Django 4.2.22 on 2025-06-05 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("post_date", models.DateTimeField(auto_now_add=True)),
                (
                    "opportunity_type",
                    models.CharField(
                        choices=[
                            ("job", "Full‐Time Job"),
                            ("internship", "Internship"),
                            ("volunteer", "Volunteer"),
                            ("scholarship", "Scholarship/Fellowship"),
                            ("training", "Training/Online Course"),
                        ],
                        help_text="Choose one of: job, internship, volunteer, scholarship, training",
                        max_length=50,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="(optional) City, Country, or Online",
                        max_length=150,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunities",
                        to="opportunities.category",
                    ),
                ),
            ],
        ),
    ]
