# Generated by Django 4.2.22 on 2025-07-14 08:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("opportunities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="deadline",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="opportunity",
            name="instructions",
            field=models.TextField(
                default="not provided",
                help_text="How to apply or get involved. Include links if applicable.",
            ),
            preserve_default=False,
        ),
    ]
