# Generated by Django 4.2.22 on 2025-07-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunities", "0002_opportunity_deadline_opportunity_instructions"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="company",
            field=models.CharField(
                blank=True,
                help_text="(optional) Company or Organization Name",
                max_length=255,
            ),
        ),
    ]
