# Generated by Django 4.2.22 on 2025-07-14 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("opportunities", "0003_opportunity_company"),
    ]

    operations = [
        migrations.RenameField(
            model_name="opportunity",
            old_name="company",
            new_name="organization",
        ),
    ]
