# Generated by Django 4.2.22 on 2025-07-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunities", "0004_rename_company_opportunity_organization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunity",
            name="opportunity_type",
            field=models.CharField(
                choices=[
                    ("job", "Full‐Time Job"),
                    ("internship", "Internship"),
                    ("volunteer", "Volunteer"),
                    ("scholarship", "Scholarship"),
                    ("fellowship", "Fellowship"),
                    ("training", "Training/Online Course"),
                ],
                help_text="Choose one of: job, internship, volunteer, scholarship, training",
                max_length=50,
            ),
        ),
    ]
