# Generated by Django 4.2.22 on 2025-08-22 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunities", "0005_alter_opportunity_opportunity_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="opportunity",
            name="instructions",
        ),
        migrations.RemoveField(
            model_name="opportunity",
            name="opportunity_type",
        ),
        migrations.AddField(
            model_name="opportunity",
            name="benefits",
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="opportunity",
            name="eligibility",
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="opportunity",
            name="process",
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
