# Generated by Django 4.2.22 on 2025-08-22 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunities", "0006_remove_opportunity_instructions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunity",
            name="benefits",
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="eligibility",
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="process",
            field=models.TextField(default=None),
        ),
    ]
