# Generated by Django 4.2.22 on 2025-06-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Nomination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nominee_name", models.CharField(max_length=200)),
                (
                    "nominee_email",
                    models.EmailField(
                        blank=True,
                        help_text="(Optional) Email address of the nominee",
                        max_length=254,
                    ),
                ),
                (
                    "nominee_institution",
                    models.CharField(
                        help_text="Institution or school where the nominee teaches",
                        max_length=200,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Teacher of the Month", "Teacher of the Month"),
                            ("Teacher of the Year", "Teacher of the Year"),
                            ("Other", "Other"),
                        ],
                        default="Teacher of the Month",
                        help_text="Select the nomination category",
                        max_length=50,
                    ),
                ),
                (
                    "rationale",
                    models.TextField(
                        help_text="Explain why this teacher deserves the recognition"
                    ),
                ),
                (
                    "nominated_by_name",
                    models.CharField(
                        help_text="Name of the person making this nomination",
                        max_length=150,
                    ),
                ),
                (
                    "nominated_by_email",
                    models.EmailField(
                        blank=True,
                        help_text="(Optional) Contact email of the nominator",
                        max_length=254,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved",
                    models.BooleanField(
                        default=False,
                        help_text="Set to True once an admin approves this nomination",
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
    ]
