# Generated by Django 4.2.22 on 2025-10-03 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nominations_awards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="nomination",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Upload a photo for Teacher of the Month/Year",
                null=True,
                upload_to="nominations/",
            ),
        ),
    ]
