# Generated by Django 4.2.22 on 2025-06-05 18:11

from django.db import migrations, models
import django.db.models.deletion
import resources.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "file",
                    models.FileField(
                        upload_to=resources.models.resource_file_upload_path
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Enter 0.00 if this resource is free",
                        max_digits=8,
                    ),
                ),
                (
                    "uploader_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the person who uploaded this resource (e.g. Teacher’s name)",
                        max_length=150,
                    ),
                ),
                (
                    "uploader_email",
                    models.EmailField(
                        blank=True,
                        help_text="Email address of the uploader (optional)",
                        max_length=254,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ResourcePurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("buyer_name", models.CharField(max_length=150)),
                ("buyer_email", models.EmailField(max_length=254)),
                ("purchased_at", models.DateTimeField(auto_now_add=True)),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        help_text="Optional: payment transaction reference",
                        max_length=100,
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to="resources.resource",
                    ),
                ),
            ],
        ),
    ]
